baseURL = 'http://tuansondesigns.com'
languageCode = 'en-us'
title = 'Tuan Son - Kisei'
[params]
ogImage = "/images/open-graph-image.jpg"
[markup]
    [markup.goldmark.parser]
        wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
        unsafe= true
    [markup.goldmark.parser.attribute]
        block = true
        title = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[[menus.main]]
  name = "Work"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "About"
  pageRef = "/about"
  weight = 20

[[menus.main]]
  name = "Resume (PDF)"
  url = "/Tuan_Son_Resume.pdf"
  weight = 30
  [menus.main.params]
    external = true

[[menus.main]]
  name = "Now"
  pageRef = "/now"
  weight = 40

[[menus.main]]
  name = "Colophon"
  pageRef = "/colophon"
  weight = 50

[[menus.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 60

[[menus.main]]
  name = "Slashes"
  pageRef = "/slashes"
  weight = 70
